# Configuration file for Python projects.
# See https://python-poetry.org/docs/pyproject/ and
# https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata
#
# Sort all entries alphabetically!

[tool.black]
required-version = 22
line-length = 79
target-version = ["py39"]

[tool.isort]
# profile should go on top so that it does not overwrite other settings.
profile = "black"
# Comments to put above import sections.
import_heading_future = "Future imports"
import_heading_stdlib = "Standard libraries"
import_heading_thirdparty = "Third-party libraries"
import_heading_firstparty = "First-party libraries"
import_heading_localfolder = "Local imports"
line_length = 79
# Number of blank lines around import statements.
lines_before_imports = 2
lines_after_imports = 2
lines_between_sections = 1
lines_between_types = 0
py_version = 39
# Ignore files listed in .gitignore.
skip_gitignore = true
